# Generated by Django 3.2.4 on 2021-07-04 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0002_auto_20210703_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='oderno',
        ),
    ]
