# Generated by Django 3.2.4 on 2021-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0003_remove_item_oderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
