# Generated by Django 3.2.4 on 2021-07-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0004_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Image',
        ),
        migrations.AddField(
            model_name='customer',
            name='fromAddr2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='toAddr2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='productDesc',
            field=models.CharField(max_length=100),
        ),
    ]
